### ISSUE TITLE
Tutorials examples for multiclass and multilabel labelling?

### ISSUE THREAD

**Issue by JohnGiorgi** [HazyResearch/flyingsquid#11]
Hi, thanks for making this public. I enjoyed the paper, and my team and I are excited to try this out in our work.

We have a multilabel problem and are struggling a little bit with how to apply FlyingSquid to this setup. C.2 of the appendix mentions that in the multiclass case, a one-versus-all scheme can be applied repeatedly. This makes sense in principle, but I was wondering if there was an example of this using `LabelModel` that could be provided? We went through the example notebooks, but each demonstrates a binary classification problem.

In the case of _multilabel_, I was thinking that you could follow a one-vs-all approach _without a voting scheme_ as is typically done, such that each instance in the dataset can end up with multiple labels. Is this something that can be done with FlyingSquids `LabelModel`?

**Comment by JohnGiorgi** [comment]
This turned out to be straightforward. 

For anyone who is interested, I just created one `label_model` per label and used each `label_model` to produce `probabilistic_labels`. This list of labels can be concatenated to yield a matrix of (number of examples, number of labels)!

**Comment by fredsala** [comment]
Hi John,

Thanks for your comments! Indeed, what you described is how we usually handle the multiclass case, but rather than concatenating, we combine all of the (binary) label model output parameters into one big parameter. For your case, with multilabels, concatenation should work.

Let us know if you have more questions!

**Comment by JieyuZ2** [comment]
> Hi John,
> 
> Thanks for your comments! Indeed, what you described is how we usually handle the multiclass case, but rather than concatenating, we combine all of the (binary) label model output parameters into one big parameter. For your case, with multilabels, concatenation should work.
> 
> Let us know if you have more questions!

Hi Frederic,

Could you explain a little bit how to combine all the binary models into one big model?
