### ISSUE TITLE
_triplet_method_preprocess seems to be missing break statements

### ISSUE THREAD

**Issue by coulls** [HazyResearch/flyingsquid#4]
In this loop (https://github.com/HazyResearch/flyingsquid/blob/master/flyingsquid/label_model.py#L283-L288), both the inner and outer loop are escaped once a triplet is found.

Here (https://github.com/HazyResearch/flyingsquid/blob/master/flyingsquid/label_model.py#L305-L308) and in a mirrored loop below, there is no escape for the outer loop.  That seems to be a bug as it means the entire inner loop will continue to be evaluated over and over even if a triplet was discovered.

**Comment by DanFu09** [comment]
Thanks for the bug report - I saw the bug right after your last issue too :)
